
name: Production Pipeline
permissions: write-all

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
      - "main"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Set the working directory to PageStatsReact since the project is in a sub-folder
defaults:
  run:
    working-directory: frontend

# Jobs that get executed
jobs:
  # Install job that installs cypress, builds the project and uploads the build artifact 
  build-and-cypress-install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          # Disable running of tests within install job
          runTests: false
      - run: npm install
      - run: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          if-no-files-found: error
          path: frontend/dist

  # Run tnit tests
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm install

      - name: Run Jest tests
        run: npm run test

  # Run cypress tests in chrome
  cypress-run:
    runs-on: ubuntu-22.04
    # Needs the install job to be finished
    needs: [ build-and-cypress-install, unit-tests ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: frontend
          start: npm run dev
          browser: chrome 

  # Deployment job to deploy to server using ssh
  deploy:
    runs-on: ubuntu-22.04
    needs: cypress-run
    steps:
      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy dist folder to server
        run: echo "Deployment goes here ..."